name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          cd DnD-Board.API
          dotnet build -c Release -o bin/build
      - name: Copy build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          rm: true
          strip_components: 5
          source: "/home/runner/work/DnD-Board/DnD-Board/DnD-Board.API/bin/build/"
          target: "projects/dnd-board/backend-api"

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd projects/dnd-board
            docker-compose down
            docker-compose up -d --build dnd-board-api
